## 반복문 복습

In [2]:
for i in range(1000):
  print("No : ", i+1)
  if i == 10:
    break
  print("Hello World")
  print("안녕하세요")

No :  1
Hello World
안녕하세요
No :  2
Hello World
안녕하세요
No :  3
Hello World
안녕하세요
No :  4
Hello World
안녕하세요
No :  5
Hello World
안녕하세요
No :  6
Hello World
안녕하세요
No :  7
Hello World
안녕하세요
No :  8
Hello World
안녕하세요
No :  9
Hello World
안녕하세요
No :  10
Hello World
안녕하세요
No :  11


In [9]:
a = "Kaggle"

for i in a:
  print(i)
  if i == "a":
    break

K
a


- 리스트의 값이 존재

In [14]:
numbers = [1,2,3,4,5]
sum  = 0

for num in numbers:
  print("numbers:", num)
  sum = sum + num
  print("total:", sum)

  print("-- 최종결괏값 --")
  print(sum)

numbers: 1
total: 1
-- 최종결괏값 --
1
numbers: 2
total: 3
-- 최종결괏값 --
3
numbers: 3
total: 6
-- 최종결괏값 --
6
numbers: 4
total: 10
-- 최종결괏값 --
10
numbers: 5
total: 15
-- 최종결괏값 --
15


In [19]:
fruits = ['apple','kiwi','manggo']
newlist=[]

# apple : a가 있나요? 있네요. newlist에 추가하세요.
# kiwi : a가 있나요? 없네요. 그럼 넘어가요.
# mango : a가 있나요? 있네요. newlist에 추가하세요.
for fruit in fruits:
  print("조건문 밖 :",fruit)
  if "a" in fruit:
   print("조건문 안쪽 :", fruit)
   newlist.append(fruit)
print(newlist)

조건문 밖 : apple
조건문 안쪽 : apple
조건문 밖 : kiwi
조건문 밖 : manggo
조건문 안쪽 : manggo
['apple', 'manggo']


## While Loop

While문 : 분석할때 거의 사용안함, 개발할때 많이 사용

In [20]:
i = 1
while i < 10: #참일때만 반복문 코드실행됨
  # 코드
  print(i)
  i +=1 # 1씩 증가
    #i -=1 #1씩 감소

1
2
3
4
5
6
7
8
9


## 사용자 정의함수
- 내가 필요에 의해 직접 함수를 작성


In [21]:
def 함수명(param1, param2):
  #코드
  return None



In [22]:
def add(a = 0, b = 1):
  c = a + b
  return c

print(add(a = 5, b = 4))
print(add())

9
1


- 사칙연산 사용자 정의함수 만들기 


In [24]:
def na(a=10, b=100):
  c = a * b
  return c

print(na())


1000


In [25]:
def love(a=8,b=100):
  c = a / b
  return c
print(love(a=10,b=20))
print(love())


0.5
0.08


In [26]:
def add(a, b) :
  return a + b
print(add(1,2))
def cal(a, b) :
  return a - b
print(cal(1,2))
def cal(a, b) :
  return a * b
print(cal(1,2))
def cal(a, b) :
  return a / b
print(cal(1,2))

3
-1
2
0.5


In [28]:
def subtract(a,b):
   return a-b

print(subtract(a=5,b=10))


-5


- 함수 문서화(매우중요)
 + 키워드 : Docsting

In [37]:
def subtract(a,b):
  """a,b를 빼는 함수

     Parameters:
     a(int):int형 숫자 a가 입력

     b(int): int형 숫자 b가 입력

     Return:
     int:반환값 
   """
  return a-b

print(subtract(a=5,b=10))
print(subtract.__doc__)

-5
a,b를 빼는 함수

     Parameters:
     a(int):int형 숫자 a가 입력

     b(int): int형 숫자 b가 입력

     Return:
     int:반환값 
   


## Numpy
- 내장모듈(=라이브러리=패키지) (X)
- 별도 라이브러리 설치 


In [38]:
import numpy as np
print(np.__version__)

1.21.6


In [41]:
temp = [1,2,3]
temp_array = np.array(temp)
print(type(temp))
print(type(temp_array))

<class 'list'>
<class 'numpy.ndarray'>


## 사칙연산

In [42]:
math_score = [90,80,100]
eng_score = [80,90,100]

# math_score + eng_score
math_array = np.array(math_score)
eng_array = np.array(eng_score)

total = math_array + eng_array
print(total)
print(type(total))

[170 170 200]
<class 'numpy.ndarray'>


In [ ]:
- 집계함수

In [45]:
print(np.min(total))
print(np.max(total))
print(np.sum(total))

170
200
540


## 차원 확인
- 배열의 차원 확인 필요

In [52]:
# 1차원 배열
temp_arr = np.array([1,2,3])
print(temp_arr.shape) # 값이 몇개?
print(temp_arr.ndim) # 몇 차원?
print(temp_arr)

(3,)
1
[1 2 3]


In [51]:
# 2차원 배열 생성
temp_arr = np.array([[1,2,3,],[4,5,6]]) # 2묶음, 3개씩
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)


(2, 3)
2
[[1 2 3]
 [4 5 6]]


In [54]:
# 3차원 배열 -> 이미지
temp_arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(temp_arr.shape)
print(temp_arr.ndim)
print(temp_arr)

(2, 2, 3)
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


## 배열 생성의 다양한 방법들
- 모두 0으로 채운다

In [1]:
import numpy as np
print(np.__version__)

1.21.6


In [2]:
temp_arr = np.zeros((3,3,3))
temp_arr

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

- a모두 1로 채운다

In [3]:
temp_arr = np.ones((2,3))
temp_arr

array([[1., 1., 1.],
       [1., 1., 1.]])

- 임의의 상수값으로 채운다

In [4]:
temp_arr = np.full((3,3),5)
temp_arr

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

- 최소, 최대 숫자의 범위를 정해두고, 각 구간별로 값을 생성

In [5]:
temp_arr = np.linspace(5,10,10)
temp_arr

array([ 5.        ,  5.55555556,  6.11111111,  6.66666667,  7.22222222,
        7.77777778,  8.33333333,  8.88888889,  9.44444444, 10.        ])

- 반복문 시, 자주 등장하는 배열

In [7]:
temp_arr = np.arange(1,11,1)
temp_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

- 난수 생성

In [9]:
from numpy import random
x = random.rand()
print(x)

0.47713558758041374


In [ ]:
위와 같은 코드 다른형식 

In [10]:
import numpy 
x = numpy.random.rand()
print(x)

0.7337058404065017


- 랜덤 정수값 추출

In [11]:
from numpy import random
x = random.randint(100,size = (5))
print(x)
print(type(x))

[66 59 51 62 52]
<class 'numpy.ndarray'>


- 랜덤 배열, 실수 값 추출

In [12]:
from numpy import random
x = random.rand(2,5)
print(x)
print(type(x))

[[0.20589017 0.44450341 0.98789043 0.31725431 0.64770063]
 [0.80055663 0.52180604 0.31230452 0.25684295 0.96396122]]
<class 'numpy.ndarray'>


## NumPy 사칙연산

In [15]:
import numpy as np
array_01 = np.array([1,2,3])
array_02 = np.array([10,20,30])


# 덧셈
newArr = np.add(array_01, array_02)
print(newArr)

# 뺄셈 
newArr = np.subtract(array_01, array_02)
print(newArr)

# 나누기
newArr = np.divide(array_01, array_02)
print(newArr)

# 거듭제곱
array_01 = np.array([1, 2, 3])
array_02 = np.array([2, 4, 2])
newArr = np.power(array_01, array_02)
print(newArr)




[11 22 33]
[ -9 -18 -27]
[0.1 0.1 0.1]
[ 1 16  9]


소수점정렬
- 소수점을 정렬하는 다양한 방법

In [17]:
# 소수점 제거 
import numpy as no
temp_arr = np.trunc([-1.23,1.23])
print(temp_arr)

temp_arr = np.fix([-1.23,1.23])
print(temp_arr)

[-1.  1.]
[-1.  1.]


In [19]:
#임의의 소숫점 자리에서 반올림
temp_arr = np.around([-1.2345678, 1.2345678],5)
print(temp_arr)

[-1.23457  1.23457]


## 조건식 (중요)
- pandas 가공
- numpy
- 조건식
 + 하나의 조건식
 + 다중 조건식

In [20]:
temp_arr = np.arange(10)
temp_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 5보다 작으면 그냥 원 값 유지
# 5보다 크면 기존 값에 곱하기 10을 해줌

In [21]:
# np.where(조건식, 참일때, 거짓일때)
np.where(temp_arr < 5, temp_arr, temp_arr * 10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

In [26]:
temp_arr = np.arange(10)
# temp_arr
cond_list = [temp_arr >5, temp_arr <2]
choice_list = [temp_arr * 2, temp_arr + 100]

# np.select (조건식 리스트, 결괏값리스트, default = )
np.select(cond_list, choice_list, default = temp_arr)

array([100, 101,   2,   3,   4,   5,  12,  14,  16,  18])

## Reshape
- 배열의 차원 또는 크기를 바꾼다
- 곱셈만 할 줄 알면 문제없음

In [28]:
import numpy as np
temp_array = np.ones((3,4))
print(temp_array.shape)
print(temp_array)

(3, 4)
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
after_reshape = temp_array.reshape(1, 12) #괄호안에 수의 곱이 12로 조합하면 결과실행
print(after_reshape.shape)
print(after_reshape)

(1, 12)
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [32]:
after_reshape = temp_array.reshape(2,-1) #-1넣으면 알아서 맞춰줌
print(after_reshape.shape)
print(after_reshape)

(2, 6)
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


# 브로드 캐스팅 (중요한 개념, 논문작성시 사용)
: 서로 다른 크기의 배열을 연산할때의 기본적인 규칙을 의미한다


## pandas 튜토리얼


In [34]:
import pandas as pd
print(pd.__version__)

1.3.5


In [35]:
temp_dict = {
    'col1' : [1,2],
    'col2' : [3,4]
} 

df = pd.DataFrame(temp_dict)
print(df)
print(type(df))

   col1  col2
0     1     3
1     2     4
<class 'pandas.core.frame.DataFrame'>


## 구글 드라이브 연동

In [36]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [42]:
DATA_PATH = '/content/drive/MyDrive/Colab Notebooks/human_AI/Basic/Chapter 3. pandas/data/Lemonade2016.csv'
lemonade = pd.read_csv(DATA_PATH)

lemonade.info() #str


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Date         31 non-null     object 
 1   Location     32 non-null     object 
 2   Lemon        32 non-null     int64  
 3   Orange       32 non-null     int64  
 4   Temperature  32 non-null     int64  
 5   Leaflets     31 non-null     float64
 6   Price        32 non-null     float64
dtypes: float64(2), int64(3), object(2)
memory usage: 1.9+ KB
